name: Playground for releasing Ansible Collections via Github Actions
on:
  push:
    tags:
      - '*'
  workflow_dispatch:
jobs:
  ansible-release:
    runs-on: ubuntu-latest
    env:
      DEFAULT_PYTHON: 3.8
      RELEASE_VERSION: 3.0.0
    steps:
      - name: Install Python ${{ env.DEFAULT_PYTHON }}
        id: python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.DEFAULT_PYTHON }}
      - run: echo "Install antsibull-changelog"
      - run: pip install antsibull-changelog==0.10.0 ansible==4.0.0
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          repository: 'CiscoDevNet/ansible-meraki'
          token: ${{ env.GITHUB_TOKEN }}
      - name: List files in repository
        run: ls ${{ github.workspace }}
      - run: mkdir -p ${{ github.workspace }}/changelogs/fragments/
      - name: Create temporary changelog file
        run: touch ${{ github.workspace }}/changelogs/fragments/tests.yaml
      - run: echo "bugfixes:" > ${{ github.workspace }}/changelogs/fragments/tests.yaml
      - run: echo "- Test" >> ${{ github.workspace }}/changelogs/fragments/tests.yaml
      - name: Generate changelog
        run: cd ${{ github.workspace }} && antsibull-changelog release --version ${{ env.RELEASE_VERSION }} -v
      - name: Commit new changelog
        run: git checkout -b release/v${{ env.RELEASE_VERSION }} && git add . && git commit -m "Update changelog for ${{ env.RELEASE_VERSION }}"
      - name: Push branch
        run: gh 