name: Playground for releasing Ansible Collections via Github Actions
on:
  push:
    tags:
      - '*'
jobs:
  generate-changelog:
    runs-on: ubuntu-latest
    steps:
      - run echo "Hello world"