name: Playground for releasing Ansible Collections via Github Actions
on:
  push:
    tags:
      - '*'
  workflow_dispatch:
jobs:
  generate-changelog:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Generating changelog"
      - run: pip install antsibull-changelog==0.10.0
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: List files in repository
        run: ls ${{ github.workspace }}
