name: Playground for releasing Ansible Collections via Github Actions
on:
  push:
    tags:
      - '*'
  workflow_dispatch:
jobs:
  generate-changelog:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello world"