name: Playground for releasing Ansible Collections via Github Actions
on:
  push:
    tags:
      - '*'
  workflow_dispatch:
jobs:
  ansible-release:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Install antsibull-changelog"
      - run: pip install antsibull-changelog==0.10.0
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          repository: 'CiscoDevNet/ansible-meraki'
      - name: List files in repository
        run: ls ${{ github.workspace }}
      - name: Create temporary changelog file
        run: echo "bugfixes:" > ${{ github.workspace }}/changelog/fragments/tests.yaml
      - run: echo "- Test" >> ${{ github.workspace }}/changelog/fragments/tests.yaml
      - name: Generate changelog
        run: cd ${{ github.workspace }} && antsibull-changelog release
        