name: Playground for releasing Ansible Collections via Github Actions
on:
  push:
jobs:
  ansible-release:
    runs-on: ubuntu-latest
    env:
      DEFAULT_PYTHON: '3.10'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install Python ${{ env.DEFAULT_PYTHON }}
        id: python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.DEFAULT_PYTHON }}
      - name: Modify README.md
        steps:
          - echo "Modify file" >> README.md
      - name: Commit chnages to new branch
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit-message: Prepare for something
          branch: feature-123
          create_branch: true

